apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible
  template:
    metadata:
      labels:
        app: ansible
    spec:
      containers:
      - name: ansible
        image: shreyasing27/ansible:latest
        command: ["tail", "-f", "/dev/null"]
